spring:
  application:
    name: mscartoes
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  listener:
    simple:
      auto-startup: true
mq:
  queues:
    emissao-cartoes: emissao-cartoes

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:cursoms-eureka-user-pass@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log